### ISSUE TITLE
End goal

### ISSUE THREAD

**Issue by jtl999** [ledstrain/wiki.ledstrain.org#1]
I apologize for taking this discussion off the forum, but what's the end goal of this repository? 

Right now you have just a single demo file, that doesn't mean much (no offense intended)

I think I've said this before, but part of the reason I think making a wki/centralized database is difficult and an exercise in frustration, is that it's hard to document an issue that's so subjective and different for so many people, similar to reading reviews for things like televisions, or speaker systems (if you understand my analogy).

Having some sticky/pinned posts on the forum with some key information might be useful for new people, the question is, what?

**Comment by tyler71** [comment]
Every few months there will be a call for organizing data in some way.
A few hours spent setting something up that I end up deleting due to lack of use.

This setup can stay up more or less permanently, is accessible for anyone to change and separates the complexity of the design of the site using pelicans static site generator and its actual content.

Assuming a user wishes to contribute some kind of content, they may do so without waiting for me to create a "solution" again and can make a pull request anytime they want.
If someone wants to configure the look and feel of the site, they can make a pull request here
https://github.com/Ledstrain/ledstrain.github.io
It is currently the demo which I agree doesn't look very good at all.
However at anytime if someone wants to make it look great, that is now possible.

The end goal then, is to provide a more permanent outlet for content for those who want to use it.
So for now, it's the permanent "solution" to those who want to try and organize the current findings.

**Comment by jtl999** [comment]
Thanks.

I'm very busy these days, but I wouldn't mind helping less technical users organize their findings and "reports" (if you will) onto the static site. But I think my above concerns still stand.
